name: Build Test Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1          
    - uses: actions/setup-dotnet@v4.0.0

    - run: dotnet restore
    - run: dotnet build --configuration Release --no-restore
    - run: dotnet pack -v normal -c Release --include-symbols --include-source ch1seL.RazorViewRender
    - run: dotnet nuget push "./**/bin/Release/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
